services:
  db:
    image: mysql:latest
    container_name: mysql_containerAUTOMARKET-users
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usersAutomarket
      MYSQL_USER: juandiego
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
volumes:
  db_data:
    driver: local
